//! Put the mark on the executable itself.
//!
//! The window asks for its icon at runtime (`app::window_icon`), which covers
//! the taskbar and Alt-Tab while Zero is open. Explorer, a pinned shortcut and
//! the Start menu read a *resource* compiled into the binary instead, so that
//! one has to be linked in here or the file shows Rust's default icon.
//!
//! `zero.ico` is generated by `tools/make_icon.py` from the same geometry the
//! chrome draws; regenerate it there rather than editing it.

fn main() {
    println!("cargo:rerun-if-changed=zero.ico");
    #[cfg(windows)]
    {
        // A missing resource compiler is not a reason to fail the build: the
        // browser runs perfectly well with the default file icon.
        if let Err(error) = winresource::WindowsResource::new()
            .set_icon("zero.ico")
            .set("FileDescription", "Zero Browser")
            .set("ProductName", "Zero")
            .compile()
        {
            println!("cargo:warning=no icon on the executable: {error}");
        }
    }
}
